name: build

on: [push, pull_request]

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, pypy3]

    steps:
    - uses: actions/checkout@v2

    - uses: extractions/setup-just@v1

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: just install-dev

    - name: Lint
      if: matrix.python-version != 'pypy3'
      run: just lint

    - name: Test
      run: just test

    - uses: codecov/codecov-action@v1

  deploy:
    needs: test
    if: startsWith(github.event.ref, 'refs/tags')

    name: Deploy Python package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Check tag against package version
      run: grep '__version__' src/serde/__init__.py | grep -q "'${GITHUB_REF#refs/tags/}'"

    - name: Install dependencies
      run: pip install --upgrade setuptools twine wheel

    - name: Build distribution
      run: python setup.py sdist bdist_wheel

    - name: Publish artefacts
      run: twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
